import type { Metadata } from "next";
import HeaderActions from "./components/HeaderActions";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-[#111]`}>
        <header className="border-b border-gray-200">
          <nav className="max-w-4xl mx-auto px-6 h-14 flex items-center justify-between">
            <a href="/" className="font-semibold tracking-tight">SPiKaR Blog</a>
            <HeaderActions />
          </nav>
        </header>
        <main className="min-h-[calc(100vh-56px)]">{children}</main>
        <footer className="border-t border-gray-200 text-xs text-gray-500">
          <div className="max-w-4xl mx-auto px-6 py-4">© Mini Blog - powered by SPiKaR</div>
        </footer>
      </body>
    </html>
  );
}
